- project:
    name: rdo-infra/weirdo
    templates: []
    check:
      jobs:
        - legacy-weirdo-ansible-lint
        - legacy-weirdo-docs:
            files:
              - ^docs/.*$
              - ^.*\.rst$
        - legacy-weirdo-integration-newton-packstack-scenario001:
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/puppet.*$
        - legacy-weirdo-integration-ocata-packstack-scenario002:
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/puppet.*$
        - legacy-weirdo-integration-pike-packstack-scenario002:
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/puppet.*$
        - legacy-weirdo-integration-master-packstack-scenario003:
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/puppet.*$
        - legacy-weirdo-integration-newton-puppet-scenario001:
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/packstack.*$
        - legacy-weirdo-integration-ocata-puppet-scenario002:
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/packstack.*$
        - legacy-weirdo-integration-pike-puppet-scenario002:
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/packstack.*$
        - legacy-weirdo-integration-master-puppet-scenario003:
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/packstack.*$
        - legacy-weirdo-integration-master-puppet-scenario004:
            voting: false
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/packstack.*$
    experimental:
      jobs:
        - legacy-weirdo-integration-newton-packstack-scenario003:
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/puppet.*$
        - legacy-weirdo-integration-ocata-packstack-scenario002:
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/puppet.*$
        - legacy-weirdo-integration-pike-packstack-scenario001:
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/puppet.*$
        - legacy-weirdo-integration-master-packstack-scenario001:
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/puppet.*$
        - legacy-weirdo-integration-newton-puppet-scenario003:
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/packstack.*$
        - legacy-weirdo-integration-ocata-puppet-scenario002:
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/packstack.*$
        - legacy-weirdo-integration-pike-puppet-scenario001:
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/packstack.*$
        - legacy-weirdo-integration-master-puppet-scenario001:
            irrelevant-files:
              - ^.*README.rst$
              - ^.gitignore$
              - ^docs/.*$
              - ^playbooks/logs-ci-centos.yml$
              - ^playbooks/packstack.*$
